import type { CategoryId } from '../shared/types.js';

// Catalogue de DÉMONSTRATION : vrais noms de produits, prix de référence
// APPROXIMATIFS et fictifs. Sert uniquement quand aucune source réelle n'est configurée.
// Format : [catégorie, marque, titre, prix neuf de référence (€), reconditionnable]

export type DemoProduct = [CategoryId, string, string, number, boolean];

export const DEMO_CATALOG: DemoProduct[] = [
  // Processeurs
  ['cpu', 'AMD', 'Processeur AMD Ryzen 7 9800X3D (4.7 GHz / 5.2 GHz) AM5', 479, false],
  ['cpu', 'AMD', 'Processeur AMD Ryzen 7 7800X3D (4.2 GHz / 5.0 GHz) AM5', 369, true],
  ['cpu', 'AMD', 'Processeur AMD Ryzen 5 9600X (3.9 GHz / 5.4 GHz) AM5', 229, false],
  ['cpu', 'AMD', 'Processeur AMD Ryzen 5 7600 (3.8 GHz / 5.1 GHz) AM5', 169, true],
  ['cpu', 'AMD', 'Processeur AMD Ryzen 9 9950X (4.3 GHz / 5.7 GHz) AM5', 599, false],
  ['cpu', 'AMD', 'Processeur AMD Ryzen 5 5600X (3.7 GHz / 4.6 GHz) AM4', 119, true],
  ['cpu', 'Intel', 'Processeur Intel Core Ultra 7 265K (3.9 GHz / 5.5 GHz) LGA1851', 319, false],
  ['cpu', 'Intel', 'Processeur Intel Core Ultra 5 245K (4.2 GHz / 5.2 GHz) LGA1851', 239, false],
  ['cpu', 'Intel', 'Processeur Intel Core i5-14600K (3.5 GHz / 5.3 GHz) LGA1700', 229, true],
  ['cpu', 'Intel', 'Processeur Intel Core i7-14700K (3.4 GHz / 5.6 GHz) LGA1700', 349, true],
  // Cartes graphiques
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 5090 32 Go GDDR7', 2349, false],
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 5080 16 Go GDDR7', 1169, false],
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 5070 Ti 16 Go GDDR7', 829, false],
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 5070 12 Go GDDR7', 599, false],
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 5060 Ti 16 Go GDDR7', 449, false],
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 4070 Super 12 Go GDDR6X', 619, true],
  ['gpu', 'NVIDIA', 'Carte graphique NVIDIA GeForce RTX 3060 12 Go GDDR6', 279, true],
  ['gpu', 'AMD', 'Carte graphique AMD Radeon RX 9070 XT 16 Go GDDR6', 689, false],
  ['gpu', 'AMD', 'Carte graphique AMD Radeon RX 9060 XT 16 Go GDDR6', 379, false],
  ['gpu', 'AMD', 'Carte graphique AMD Radeon RX 7800 XT 16 Go GDDR6', 499, true],
  ['gpu', 'Intel', 'Carte graphique Intel Arc B580 12 Go GDDR6', 279, false],
  // Cartes mères
  ['motherboard', 'ASUS', 'Carte mère ASUS TUF Gaming B650-PLUS WiFi AM5 ATX', 199, true],
  ['motherboard', 'MSI', 'Carte mère MSI MAG X870 Tomahawk WiFi AM5 ATX', 299, false],
  ['motherboard', 'Gigabyte', 'Carte mère Gigabyte B850 Aorus Elite WiFi7 AM5 ATX', 239, false],
  ['motherboard', 'ASRock', 'Carte mère ASRock B650M Pro RS WiFi AM5 Micro-ATX', 149, false],
  ['motherboard', 'MSI', 'Carte mère MSI PRO Z890-P WiFi LGA1851 ATX', 249, false],
  // RAM
  ['ram', 'Corsair', 'Mémoire RAM Corsair Vengeance DDR5 32 Go (2 x 16 Go) 6000 MHz CL30', 109, false],
  ['ram', 'G.Skill', 'Mémoire RAM G.Skill Trident Z5 Neo RGB DDR5 64 Go (2 x 32 Go) 6000 MHz CL30', 219, false],
  ['ram', 'Kingston', 'Mémoire RAM Kingston Fury Beast DDR4 32 Go (2 x 16 Go) 3200 MHz CL16', 69, true],
  ['ram', 'Crucial', 'Mémoire RAM Crucial SO-DIMM DDR5 16 Go 5600 MHz', 45, false],
  ['ram', 'Kingston', 'Mémoire RAM serveur Kingston DDR5 ECC RDIMM 64 Go 4800 MHz', 329, true],
  // SSD
  ['ssd', 'Samsung', 'SSD Samsung 990 Pro NVMe M.2 PCIe 4.0 2 To', 169, false],
  ['ssd', 'Samsung', 'SSD Samsung 9100 Pro NVMe M.2 PCIe 5.0 2 To', 259, false],
  ['ssd', 'WD', 'SSD WD_Black SN850X NVMe M.2 PCIe 4.0 1 To', 89, false],
  ['ssd', 'Crucial', 'SSD Crucial T500 NVMe M.2 PCIe 4.0 2 To', 139, false],
  ['ssd', 'Kingston', 'SSD Kingston NV3 NVMe M.2 PCIe 4.0 1 To', 59, false],
  ['ssd', 'Samsung', 'SSD Samsung 870 EVO SATA 2.5 pouces 1 To', 89, true],
  // HDD
  ['hdd', 'Seagate', 'Disque dur Seagate IronWolf 8 To 3.5 pouces 7200 tr/min NAS', 199, true],
  ['hdd', 'WD', 'Disque dur WD Red Plus 4 To 3.5 pouces 5400 tr/min NAS', 115, true],
  ['hdd', 'Seagate', 'Disque dur Seagate Exos X20 20 To 3.5 pouces SATA entreprise', 389, true],
  ['hdd', 'Toshiba', 'Disque dur Toshiba N300 12 To 3.5 pouces NAS', 269, true],
  ['hdd', 'Seagate', 'Disque dur Seagate BarraCuda 2 To 3.5 pouces 7200 tr/min', 65, true],
  // Alimentations / boîtiers / refroidissement
  ['psu', 'Corsair', 'Alimentation Corsair RM850e 850W 80 Plus Gold ATX 3.1 modulaire', 119, true],
  ['psu', 'Seasonic', 'Alimentation Seasonic Focus GX-1000 1000W 80 Plus Gold ATX 3.1', 169, false],
  ['psu', 'be quiet!', 'Alimentation be quiet! Pure Power 12 M 750W 80 Plus Gold', 99, false],
  ['case', 'Lian Li', 'Boîtier PC Lian Li O11 Dynamic EVO moyen tour verre trempé', 159, true],
  ['case', 'Fractal Design', 'Boîtier PC Fractal Design North moyen tour ATX', 139, false],
  ['case', 'NZXT', 'Boîtier PC NZXT H5 Flow moyen tour ATX', 94, false],
  ['cooling', 'Thermalright', 'Ventirad Thermalright Peerless Assassin 120 SE', 39, false],
  ['cooling', 'Noctua', 'Ventirad Noctua NH-D15 G2', 149, false],
  ['cooling', 'Arctic', 'Watercooling AIO Arctic Liquid Freezer III 360', 99, false],
  ['fan', 'Arctic', 'Ventilateur Arctic P12 PWM PST 120mm (pack de 5)', 29, false],
  ['fan', 'Noctua', 'Ventilateur Noctua NF-A12x25 PWM 120mm', 34, false],
  // Pâte thermique
  ['thermal-paste', 'Arctic', 'Pâte thermique Arctic MX-6 4 g', 8, false],
  ['thermal-paste', 'Arctic', 'Pâte thermique Arctic MX-4 20 g', 17, false],
  ['thermal-paste', 'Thermal Grizzly', 'Pâte thermique Thermal Grizzly Kryonaut 1 g', 11, false],
  ['thermal-paste', 'Noctua', 'Pâte thermique Noctua NT-H2 3.5 g', 13, false],
  ['thermal-paste', 'Thermal Grizzly', 'Pad thermique Thermal Grizzly KryoSheet 33 x 33 mm', 19, false],
  // PC portables
  ['laptop', 'Apple', 'Apple MacBook Air 13 pouces M4 16 Go 256 Go SSD', 1199, true],
  ['laptop', 'Apple', 'Apple MacBook Pro 14 pouces M4 Pro 24 Go 512 Go SSD', 2399, true],
  ['laptop', 'Apple', 'Apple MacBook Air 13 pouces M1 8 Go 256 Go SSD', 799, true],
  ['laptop', 'Lenovo', 'PC portable Lenovo ThinkPad T14 Gen 5 Intel Core Ultra 5 16 Go 512 Go SSD', 1149, true],
  ['laptop', 'Lenovo', 'PC portable Lenovo ThinkPad T480 Intel Core i5-8350U 16 Go 256 Go SSD', 649, true],
  ['laptop', 'Dell', 'PC portable Dell Latitude 7420 Intel Core i7-1185G7 16 Go 512 Go SSD', 1099, true],
  ['laptop', 'ASUS', 'PC portable gamer ASUS ROG Strix G16 RTX 5070 Ti Intel Core Ultra 9 32 Go 1 To', 2299, true],
  ['laptop', 'Lenovo', 'PC portable gamer Lenovo Legion 5 RTX 5060 AMD Ryzen 7 16 Go 1 To', 1399, true],
  ['laptop', 'ASUS', 'PC portable ASUS Zenbook 14 OLED Intel Core Ultra 7 16 Go 1 To', 1099, true],
  ['laptop', 'HP', 'PC portable HP EliteBook 840 G8 Intel Core i5-1145G7 16 Go 256 Go SSD', 899, true],
  // PC fixes / mini PC
  ['desktop', 'Apple', 'Apple Mac mini M4 16 Go 256 Go SSD', 699, true],
  ['desktop', 'Apple', 'Apple Mac Studio M4 Max 36 Go 512 Go SSD', 2499, true],
  ['desktop', 'Dell', 'PC de bureau Dell OptiPlex 7090 Micro Intel Core i5-10500T 16 Go 256 Go SSD', 699, true],
  ['desktop', 'HP', 'PC de bureau HP ProDesk 600 G6 SFF Intel Core i5-10500 16 Go 512 Go SSD', 649, true],
  ['desktop', 'Minisforum', 'Mini PC Minisforum UM790 Pro AMD Ryzen 9 7940HS 32 Go 1 To', 579, false],
  // Smartphones
  ['smartphone', 'Apple', 'Apple iPhone 17 Pro 256 Go', 1329, true],
  ['smartphone', 'Apple', 'Apple iPhone 17 256 Go', 969, true],
  ['smartphone', 'Apple', 'Apple iPhone 16 128 Go', 869, true],
  ['smartphone', 'Apple', 'Apple iPhone 15 128 Go', 749, true],
  ['smartphone', 'Apple', 'Apple iPhone 13 128 Go', 559, true],
  ['smartphone', 'Samsung', 'Samsung Galaxy S25 Ultra 256 Go', 1469, true],
  ['smartphone', 'Samsung', 'Samsung Galaxy S25 128 Go', 899, true],
  ['smartphone', 'Samsung', 'Samsung Galaxy A56 5G 128 Go', 449, true],
  ['smartphone', 'Google', 'Google Pixel 10 Pro 256 Go', 1199, true],
  ['smartphone', 'Google', 'Google Pixel 9a 128 Go', 549, true],
  ['smartphone', 'Xiaomi', 'Xiaomi Redmi Note 14 Pro 5G 256 Go', 399, true],
  ['smartphone', 'Fairphone', 'Fairphone 5 256 Go', 699, true],
  // Tablettes / montres
  ['tablet', 'Apple', 'Apple iPad Air 11 pouces M3 Wi-Fi 128 Go', 719, true],
  ['tablet', 'Apple', 'Apple iPad 11 pouces A16 Wi-Fi 128 Go', 409, true],
  ['tablet', 'Apple', 'Apple iPad Pro 11 pouces M4 Wi-Fi 256 Go', 1219, true],
  ['tablet', 'Samsung', 'Samsung Galaxy Tab S10 FE 128 Go Wi-Fi', 549, true],
  ['tablet', 'Microsoft', 'Microsoft Surface Pro 11 Snapdragon X Plus 16 Go 256 Go', 1269, true],
  ['tablet', 'Lenovo', 'Lenovo Tab P12 128 Go Wi-Fi', 329, true],
  ['smartwatch', 'Apple', 'Apple Watch Series 11 GPS 42 mm', 449, true],
  ['smartwatch', 'Samsung', 'Samsung Galaxy Watch 8 44 mm Bluetooth', 329, true],
  // Serveurs
  ['server', 'Dell', 'Serveur Dell PowerEdge R760 rack 2U Intel Xeon Silver 4410Y 32 Go', 5490, true],
  ['server', 'Dell', 'Serveur Dell PowerEdge R740 rack 2U 2x Intel Xeon Gold 6130 128 Go', 3290, true],
  ['server', 'HPE', 'Serveur HPE ProLiant DL380 Gen10 rack 2U 2x Intel Xeon Silver 4214 64 Go', 2890, true],
  ['server', 'HPE', 'Serveur HPE ProLiant MicroServer Gen11 Intel Xeon E-2434 16 Go', 1190, true],
  ['server', 'Lenovo', 'Serveur Lenovo ThinkSystem SR650 V3 rack 2U Intel Xeon Silver 32 Go', 5890, true],
  ['server', 'Supermicro', 'Serveur Supermicro SYS-1029P rack 1U 2x Intel Xeon Silver 64 Go', 1890, true],
  // NAS
  ['nas', 'Synology', 'NAS Synology DiskStation DS224+ 2 baies', 349, true],
  ['nas', 'Synology', 'NAS Synology DiskStation DS925+ 4 baies', 639, false],
  ['nas', 'Synology', 'NAS Synology DiskStation DS1522+ 5 baies', 799, true],
  ['nas', 'QNAP', 'NAS QNAP TS-464 4 baies Intel Celeron N5105', 579, true],
  ['nas', 'UGREEN', 'NAS UGREEN NASync DXP4800 Plus 4 baies', 699, false],
  ['nas', 'TerraMaster', 'NAS TerraMaster F4-424 Pro 4 baies', 649, false],
  // Réseau / onduleurs
  ['network', 'Ubiquiti', 'Routeur Ubiquiti UniFi Cloud Gateway Ultra', 139, true],
  ['network', 'TP-Link', 'Switch TP-Link TL-SG108 8 ports Gigabit', 22, false],
  ['network', 'TP-Link', 'Système Wi-Fi 7 mesh TP-Link Deco BE65 (pack de 2)', 399, true],
  ['network', 'Ubiquiti', 'Point d accès Ubiquiti UniFi U7 Pro Wi-Fi 7', 199, false],
  ['ups', 'APC', 'Onduleur APC Back-UPS Pro 1500VA', 269, true],
  ['ups', 'Eaton', 'Onduleur Eaton 5E 1100VA USB', 139, false],
  // Écrans / périphériques
  ['monitor', 'Samsung', 'Écran PC Samsung Odyssey G5 27 pouces QHD 180Hz', 229, true],
  ['monitor', 'LG', 'Écran PC LG UltraGear 27GR95QE OLED 27 pouces 240Hz', 699, true],
  ['monitor', 'Dell', 'Écran PC Dell UltraSharp U2724D 27 pouces QHD', 369, true],
  ['keyboard', 'Logitech', 'Clavier Logitech MX Keys S AZERTY', 109, true],
  ['keyboard', 'Keychron', 'Clavier mécanique Keychron K8 Pro AZERTY', 119, false],
  ['mouse', 'Logitech', 'Souris Logitech MX Master 3S', 99, true],
  ['mouse', 'Logitech', 'Souris gaming Logitech G Pro X Superlight 2', 149, true],
  ['headset', 'Sony', 'Casque Sony WH-1000XM6 à réduction de bruit', 449, true],
  ['headset', 'Apple', 'Écouteurs Apple AirPods Pro 3', 279, true],
  ['webcam', 'Logitech', 'Webcam Logitech Brio 4K', 179, true],
  ['printer', 'Brother', 'Imprimante laser Brother HL-L2445DW', 129, false],
  ['console', 'Sony', 'Console Sony PlayStation 5 Slim édition standard', 499, true],
  ['console', 'Nintendo', 'Console Nintendo Switch 2', 469, true],
  ['console', 'Valve', 'Console portable Valve Steam Deck OLED 512 Go', 569, true],
  // Stockage externe / cartes mémoire
  ['external-storage', 'Samsung', 'SSD externe Samsung T7 Shield USB 3.2 2 To', 149, false],
  ['external-storage', 'WD', 'Disque dur externe WD My Passport 5 To USB 3.0', 139, false],
  ['memory-card', 'SanDisk', 'Carte microSDXC SanDisk Extreme 256 Go A2 V30', 29, false],
  ['memory-card', 'Samsung', 'Clé USB Samsung BAR Plus 128 Go USB 3.1', 19, false],
  // Câbles / chargeurs / accessoires
  ['cable', 'Anker', 'Câble Anker USB-C vers USB-C 240W 1.8 m', 15, false],
  ['cable', 'UGREEN', 'Câble HDMI 2.1 UGREEN 8K 2 m', 14, false],
  ['cable', 'Cable Matters', 'Câble DisplayPort 2.1 Cable Matters 2 m', 24, false],
  ['cable', 'UGREEN', 'Câble réseau RJ45 Cat 8 UGREEN 5 m', 12, false],
  ['cable', 'StarTech', 'Câble SATA III StarTech 50 cm (pack de 2)', 9, false],
  ['cable', 'Anker', 'Hub USB-C Anker 7 en 1 HDMI 4K', 39, false],
  ['charger', 'Anker', 'Chargeur Anker Nano 65W USB-C GaN', 45, false],
  ['charger', 'Apple', 'Chargeur Apple USB-C 20W', 25, false],
  ['charger', 'UGREEN', 'Chargeur UGREEN Nexode 100W 4 ports GaN', 59, false],
  ['charger', 'Anker', 'Batterie externe Anker 737 PowerCore 24000 mAh 140W', 99, false],
  ['charger', 'Lenovo', 'Chargeur Lenovo USB-C 65W pour ThinkPad', 49, true],
  ['accessory', 'Spigen', 'Coque Spigen Ultra Hybrid pour iPhone 16', 19, false],
  ['accessory', 'Belkin', 'Protection écran verre trempé Belkin pour iPhone 16', 29, false],
  ['accessory', 'Apple', 'Stylet Apple Pencil Pro', 149, true],
  ['accessory', 'iFixit', 'Kit de nettoyage et outils iFixit Pro Tech Toolkit', 79, false],
  ['accessory', 'Samsonite', 'Sacoche Samsonite pour PC portable 15.6 pouces', 69, false],
];
