import type { CategoryId } from '@shared/types';
import {
  BatteryCharging,
  Box,
  Cable,
  CircuitBoard,
  Cpu,
  Database,
  Droplet,
  Fan,
  Gamepad2,
  Gpu,
  HardDrive,
  Headphones,
  Keyboard,
  Laptop,
  MemoryStick,
  Microchip,
  Monitor,
  Mouse,
  Network,
  Package,
  PlugZap,
  Printer,
  Server,
  ShieldCheck,
  Smartphone,
  Tablet,
  Usb,
  Watch,
  Webcam,
  Wind,
  Zap,
  CodeXml,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<CategoryId, LucideIcon> = {
  cpu: Cpu,
  gpu: Gpu,
  motherboard: CircuitBoard,
  ram: MemoryStick,
  ssd: Microchip,
  hdd: HardDrive,
  psu: Zap,
  case: Box,
  cooling: Wind,
  'thermal-paste': Droplet,
  fan: Fan,
  desktop: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  smartwatch: Watch,
  server: Server,
  nas: Database,
  monitor: Monitor,
  keyboard: Keyboard,
  mouse: Mouse,
  headset: Headphones,
  webcam: Webcam,
  network: Network,
  cable: Cable,
  charger: BatteryCharging,
  'external-storage': HardDrive,
  'memory-card': Usb,
  printer: Printer,
  console: Gamepad2,
  ups: PlugZap,
  software: CodeXml,
  accessory: ShieldCheck,
  other: Package,
};

export function CategoryIcon({ category, className }: { category: CategoryId; className?: string }) {
  const Icon = ICONS[category] ?? Package;
  return <Icon className={className} aria-hidden />;
}
